- doc/talks/talks.md
Hi @peterpeterparker, I'd like to add the presentation I'm working on currently, as you mentioned in the readme that we can send you the presentations we create using deckdeckgo, so here you go!
It's in spanish as it's a work that I'm doing in the master I'm studying right now, hope it's not a problem for you 👍 
I thought it would be more useful for you to directly create a pull request in this file.
Thank you.
David.
> new talk using deckdeckgo :)

- studio/src/app/pages/core/about/app-services/app-services.tsx
> fix: add SQS to about page

- infra/handler/app/Test.hs
- infra/handler/package.yaml
- infra/handler/src/DeckGo/Presenter.hs
> use md5 checksum to avoid re-uploading presentation files

- infra/default.nix
- infra/dirty_lambda.tf
- infra/google_key_updater.tf
- infra/handler/app/Dirty.hs
- infra/handler/app/Test.hs
- infra/handler/package.yaml
- infra/handler/src/DeckGo/Handler.hs
- infra/handler/src/DeckGo/Presenter.hs
- infra/main.tf
- infra/postgres.tf
- infra/presentation_lambda.tf
- infra/sqs.tf
> Invalidate CloudFront cache on presentation update

- docs/src/app/pages/docs/slides/app-slides-container.scss
> docs(docs): add borders to slots

- webcomponents/core/src/components/reveal/deckdeckgo-reveal/deckdeckgo-reveal.tsx
Decided to take attempt my [Twitter comment](https://twitter.com/n_moore/status/1160264581991866374). Feel free to use, but also no worries if you prefer your solution! 😁
> Render reveal styles declaratively

- infra/default.nix
- infra/handler/app/Test.hs
- infra/handler/package.yaml
- infra/handler/src/DeckGo/Handler.hs
- infra/handler/src/DeckGo/Presenter.hs
- infra/nix/sources.json
> Migrate decks to PG

- webcomponents/slides/youtube/package-lock.json
- webcomponents/slides/youtube/package.json
- webcomponents/slides/youtube/src/components/youtube/deckdeckgo-youtube.tsx
> fix (#262): load youtube once

- studio/src/app/handlers/editor/events/deck/deck-events.handler.tsx
> fix(#254): possible (maybe) race condition referencing the deck while updating the list of slides

- studio/src/app/pages/editor/app-editor/app-editor.scss
- studio/src/global/theme/editor/editor-deck-rtl.scss
> fix(#253): RTL font-size em when modified through the browser

- studio/src/app/components/editor/app-editor-toolbar/app-editor-toolbar.tsx
- studio/src/app/handlers/editor/events/deck/deck-events.handler.tsx
- studio/src/app/utils/editor/reveal-slot.utils.tsx
- studio/src/global/theme/editor/editor-deck-placeholder.scss
- studio/src/global/theme/editor/editor-fullscreen.scss
> feat(#250): highlight selected element

- webpack/src/markdown/deckdeckgo-markdown-plugin.ts
> fix(#283): webpack markdown plugin remarkable import

- studio/src/app/pages/editor/app-editor/app-editor.tsx
> fix(#287): toggle fullscreen with Escape

- studio/src/app/services/editor/publish/publish.service.tsx
> feat(#289): try to publish slides not concurrently

- studio/src/app/components/editor/app-editor-toolbar/app-editor-toolbar.tsx
- studio/src/app/handlers/editor/events/deck/deck-events.handler.tsx
> fix(#243): if deck is published, delete slide in the API too

- studio/src/global/theme/content-editable.scss
> style(#285): inherit caret color

- webcomponents/core/src/components/deck/deckdeckgo-deck/deckdeckgo-deck.scss
> feat(#300): improve slide height on mobile devices when browsers are used

- studio/src/app/handlers/editor/events/deck/deck-events.handler.tsx
- studio/src/app/utils/editor/reveal-slot.utils.tsx
- studio/src/global/theme/editor/editor-deck-deck.scss
- studio/src/global/theme/editor/editor-deck-placeholder.scss
- studio/src/global/theme/editor/editor-fullscreen.scss
> fix(#302): usage of "hydrated" as word in the content should be possible

- studio/src/app/pages/core/app-settings/app-settings.tsx
> fix(#298): missing promise resolve

- studio/src/app/handlers/editor/events/deck/deck-events.handler.tsx
- studio/src/app/pages/core/app-signin/app-signin.tsx
> fix(#307): if empty, delete content field from slide in the db

- CONTRIBUTING.md
> docs: add some information about contributing 

- CHANGELOG.md
- README.md
- docs/CHANGELOG.md
- docs/docs/edit/app-edit-markdown/app-edit-markdown.md
- docs/package-lock.json
- docs/package.json
- docs/src/app/pages/docs/edit/app-edit-markdown/app-edit-markdown.tsx
- webpack/CHANGELOG.md
- webpack/package-lock.json
- webpack/package.json
- webpack/src/markdown/deckdeckgo-markdown-plugin.ts
> Optional src for the markdown webpack plugin

- studio/src/app/components/editor/actions/app-editor-actions/app-editor-actions.tsx
- studio/src/app/components/editor/actions/app-share-action/app-share-action.tsx
- studio/src/app/components/editor/app-editor-toolbar/app-editor-toolbar.scss
- studio/src/app/components/editor/app-editor-toolbar/app-editor-toolbar.tsx
- studio/src/app/helpers/editor/editor.helper.tsx
- studio/src/app/pages/core/app-dashboard/app-dashboard.tsx
- studio/src/app/pages/editor/app-editor/app-editor.tsx
- studio/src/app/popovers/editor/app-create-slide/app-create-slide.tsx
- studio/src/app/utils/editor/create-slides.utils.tsx
- studio/src/app/utils/editor/parse-slides.utils.tsx
- studio/src/components.d.ts
Solves #313 and add the clone slide feature to Studio
> feat(#313): copy/clone slide

- studio/src/app/models/api/api.deck.tsx
- studio/src/app/services/editor/publish/publish.service.tsx
> feat(#351): pass description to the publish

- CONTRIBUTING.md
- studio/src/app/components/core/app-user-info/app-user-info.tsx
- studio/src/app/components/editor/publish/app-publish-edit/app-publish-edit.tsx
- studio/src/app/definitions/unsplash.d.ts
- studio/src/app/modals/editor/app-photo/app-photo.tsx
- studio/src/app/pages/core/app-settings/app-settings.tsx
- studio/src/app/services/api/photo/api.photo.factory.service.tsx
- studio/src/app/services/api/photo/api.photo.mock.service.tsx
- studio/src/app/services/api/photo/api.photo.prod.service.tsx
- studio/src/app/services/api/photo/api.photo.service.tsx
- studio/src/app/services/api/presentation/api.presentation.factory.service.tsx
- studio/src/app/services/api/presentation/api.presentation.mock.service.tsx
- studio/src/app/services/api/presentation/api.presentation.prod.service.tsx
- studio/src/app/services/api/presentation/api.presentation.service.tsx
- studio/src/app/services/api/user/api.user.factory.service.tsx
- studio/src/app/services/api/user/api.user.mock.service.tsx
- studio/src/app/services/api/user/api.user.prod.service.tsx
- studio/src/app/services/api/user/api.user.service.tsx
- studio/src/app/services/auth/auth.service.tsx
- studio/src/app/services/core/environment/environment-config.tsx
- studio/src/app/services/editor/publish/publish.service.tsx
- studio/src/global/app-dev.ts
- studio/src/global/app.ts
> feat(#367): mock api

- README.md
- docs/CHANGELOG.md
- docs/docs/components/app-components-color/app-components-color.md
- docs/package-lock.json
- docs/package.json
- docs/src/app/pages/docs/components/app-components-color/app-components-color.tsx
- studio/package-lock.json
- studio/package.json
- studio/src/app/popovers/editor/app-color/app-color.scss
- studio/src/app/popovers/editor/app-color/app-color.tsx
- studio/src/app/popovers/editor/app-image/app-image.scss
- studio/src/global/theme/editor/editor-popover.scss
- webcomponents/color/CHANGELOG.md
- webcomponents/color/package-lock.json
- webcomponents/color/package.json
- webcomponents/color/src/components.d.ts
- webcomponents/color/src/components/color/deckdeckgo-color.tsx
- webcomponents/color/src/components/color/readme.md
> studio: opacity and reset color

- studio/src/app/handlers/editor/events/deck/deck-events.handler.tsx
- studio/src/app/pages/editor/app-editor/app-editor.tsx
> feat(#376): consider only slots as content when saving slides

- studio/src/app/components/editor/publish/app-publish-edit/app-publish-edit.scss
- studio/src/app/components/editor/publish/app-publish-edit/app-publish-edit.tsx
> feat(#385): valid title for publication with latin characters, arabic numbers, spaces and dash

- infra/nix/sources.json
> infra: update starter

- CHANGELOG.md
- docs/CHANGELOG.md
- docs/docs/components/app-components-charts/app-components-charts.md
- docs/package-lock.json
- docs/package.json
- docs/src/app/pages/docs/components/app-components-charts/app-components-charts.tsx
- webcomponents/charts/CHANGELOG.md
- webcomponents/charts/package-lock.json
- webcomponents/charts/package.json
- webcomponents/charts/src/components/charts/deckdeckgo-bar-chart/deckdeckgo-bar-chart.tsx
- webcomponents/charts/src/index.html
> feat(#340): optional bar chart titles

- studio/package-lock.json
- studio/package.json
- studio/src/app/handlers/editor/events/deck/deck-events.handler.tsx
- studio/src/app/utils/editor/create-slides.utils.tsx
- studio/src/app/utils/editor/parse-slides.utils.tsx
> fix(#404): assign slides unique key on the flight to fix reordering

- docs/docs/components/app-components-charts/app-components-charts.md
- docs/docs/components/app-components-inline-editor/app-components-inline-editor.md
- docs/docs/components/app-components-lazy-img/app-components-lazy-img.md
- docs/docs/edit/app-edit-fonts/app-edit-fonts.md
- docs/docs/edit/app-edit-markdown/app-edit-markdown.md
- docs/docs/introduction/app-introduction/app-introduction.md
- docs/docs/introduction/app-remote-control/app-remote-control.md
- docs/docs/slides/app-slide-author/app-slide-author.md
- docs/docs/slides/app-slide-big-img/app-slide-big-img.md
- docs/docs/slides/app-slide-chart/app-slide-chart.md
- docs/docs/slides/app-slide-code/app-slide-code.md
- docs/docs/slides/app-slide-gif/app-slide-gif.md
- docs/docs/slides/app-slide-qrcode/app-slide-qrcode.md
- docs/docs/slides/app-slide-youtube/app-slide-youtube.md
- docs/src/app/pages/docs/components/app-components-charts/app-components-charts.tsx
- docs/src/app/pages/docs/components/app-components-inline-editor/app-components-inline-editor.tsx
- docs/src/app/pages/docs/components/app-components-lazy-img/app-components-lazy-img.tsx
- docs/src/app/pages/docs/edit/app-edit-fonts/app-edit-fonts.tsx
- docs/src/app/pages/docs/edit/app-edit-markdown/app-edit-markdown.tsx
- docs/src/app/pages/docs/introduction/app-introduction/app-introduction.tsx
- docs/src/app/pages/docs/introduction/app-remote-control/app-remote-control.tsx
- docs/src/app/pages/docs/slides/app-slide-author/app-slide-author.tsx
- docs/src/app/pages/docs/slides/app-slide-big-img/app-slide-big-img.tsx
- docs/src/app/pages/docs/slides/app-slide-chart/app-slide-chart.tsx
- docs/src/app/pages/docs/slides/app-slide-code/app-slide-code.tsx
- docs/src/app/pages/docs/slides/app-slide-gif/app-slide-gif.tsx
- docs/src/app/pages/docs/slides/app-slide-qrcode/app-slide-qrcode.tsx
- docs/src/app/pages/docs/slides/app-slide-youtube/app-slide-youtube.tsx
I've added the videos on all the slides I thought were relevant, please check it out
> adding videos to slides

- docs/package-lock.json
- docs/package.json
- docs/src/app/components/app-footer/app-footer.scss
- docs/src/app/components/app-menu-footer/app-menu-footer.tsx
- docs/src/app/components/app-navigation/app-navigation.scss
- docs/src/app/components/app-navigation/app-navigation.tsx
- docs/src/app/components/app-theme-switcher/app-theme-switcher.scss
- docs/src/app/components/app-theme-switcher/app-theme-switcher.tsx
- docs/src/app/modals/app-navigation-modal/app-navigation-modal.scss
- docs/src/app/modals/app-navigation-modal/app-navigation-modal.tsx
- docs/src/app/pages/docs/edit/app-edit-fonts/app-edit-fonts.scss
- docs/src/app/pages/docs/introduction/app-introduction/app-introduction.scss
- docs/src/app/pages/docs/slides/app-slides-container.scss
- docs/src/components.d.ts
- docs/src/global/theme/code.scss
- docs/src/global/theme/menu.scss
- docs/src/global/theme/table.scss
- docs/src/global/theme/variables.scss
> docs: add dark and light theme switcher

- webcomponents/highlight-code/src/components/highlight-code/deckdeckgo-highlight-code.tsx
- webcomponents/highlight-code/src/index.html
Solves not displayed placeholder to #423
> fix(#423): not displayed place holder

- docs/docs/edit/app-edit-default/app-edit-default.md
- docs/docs/introduction/app-publishing/app-publishing.md
- docs/docs/introduction/app-remote-control/app-remote-control.md
- docs/docs/introduction/app-running/app-running.md
@peterpeterparker could you please review
> docs(introduction): improve grammar, markdown syntax

- studio/src/app/modals/editor/app-notes/app-notes.scss
- studio/src/app/modals/editor/app-notes/app-notes.tsx
> feat(#247): delete notes action in studio

- remote/package-lock.json
- remote/package.json
- remote/src/app/components/app-notes/app-notes.scss
- remote/src/app/components/app-notes/app-notes.tsx
- remote/src/global/app-local.ts
- remote/src/global/app.ts
> feat(#447): highlight the code of the markdown notes in the remote

- studio/src/app/components/editor/app-editor-toolbar/app-editor-toolbar.tsx
- studio/src/app/handlers/editor/events/editor/editor-events.handler.tsx
- studio/src/app/pages/editor/app-editor/app-editor.tsx
> studio: block slide if modal with keyboard is opened

- cloud/.gitignore
- cloud/functions/package-lock.json
- cloud/functions/package.json
- cloud/functions/src/index.ts
- cloud/functions/src/model/user.ts
- cloud/functions/src/watch/mailchimp/mailchimp-member.ts
- cloud/functions/src/watch/watch-user.ts
> studio: create and delete automatically Mailchimp members

- CHANGELOG.md
- studio/package-lock.json
- studio/package.json
- studio/src/app/modals/editor/app-custom-data/app-custom-data.tsx
- studio/src/app/modals/editor/app-custom-images/app-custom-images.tsx
- utils/utils/CHANGELOG.md
- utils/utils/package-lock.json
- utils/utils/package.json
- utils/utils/src/utils/utils.ts
> studio: firefox input file have to be displayed

- studio/src/app/components/editor/color/app-color-deck-slide/app-color-deck-slide.tsx
- studio/src/app/handlers/editor/events/deck/deck-events.handler.tsx
> studio: fix reset background on deck

- studio/src/app/components/editor/app-editor-toolbar/app-editor-toolbar.tsx
- studio/src/app/popovers/editor/app-element-delete/app-element-delete.scss
- studio/src/app/popovers/editor/app-element-delete/app-element-delete.tsx
- studio/src/components.d.ts
> feat(#478): confirm delete elements or slides

- studio/src/app/components/editor/color/app-color-deck-slide/app-color-deck-slide.tsx
Make colors more obvious in case of slide or deck aka display current colors as colors of the radio buttons
> feat: display the text and background color in the radio buttons

- studio/src/app/app-root.tsx
- studio/src/app/pages/core/app-settings/app-settings.tsx
- studio/src/app/services/theme/theme.service.tsx
Hey @peterpeterparker ,
Please take a look at this PR. I put in all of the code infrastructure, but I COULD NOT get the CSS to work for me 👎 So please lend me your assistance 👍 and put your  👀 on this problem. 
Another thing I want to mention is that the dark/light box is already dark in the settings form. I think it is because of https://github.com/grantlouisherman/deckdeckgo/blob/master/studio/src/global/theme/variables.scss#L80
Let me know how I can continue assisting you.
> enhancement(dark-toggle): adding UI portion of dark/light toggle

- CONTRIBUTING.md
"The following guide is there to try to guide you through the process in case you would not know where to get started. If you have further questions, of course we are happy to help, just ping us on our [Slack]"
->
"The following guide is here to try to guide you through the process of contributing to our project in case you do not know where to get started. If you have further questions, we are happy to help, just ping us on our [Slack]"
Improved grammar and readability of the sentence. 
"[DeckDeckGo] has an important learning purpose for our selves and we would be happy if its experience would also be profitable to others in terms of improvements. "
->
"[DeckDeckGo] was an important learning experience for ourselves and we would be happy if contributing to our project is also profitable …
> Improved grammar and readability of CONTRIBUTING.md

- docs/docs/introduction/app-introduction/app-introduction.md
change 'and' to 'to' so that there is only one 'and' in the sentence.
> minor change to app-introduction.md

- docs/docs/components/app-components-lazy-img/app-components-lazy-img.md
- docs/src/app/pages/docs/components/app-components-lazy-img/app-components-lazy-img.tsx
- webcomponents/lazy-img/src/components/lazy-img/deckdeckgo-lazy-img.scss
- webcomponents/lazy-img/src/components/lazy-img/deckdeckgo-lazy-img.tsx
- webcomponents/lazy-img/src/index.html
> feat(#508): smoothly display the loaded images

- studio/src/app/components/editor/app-select-target-element/app-select-target-element.tsx
- studio/src/app/components/editor/color/app-color-code/app-color-code.scss
- studio/src/app/components/editor/color/app-color-code/app-color-code.tsx
- studio/src/app/popovers/editor/app-code/app-code.tsx
- studio/src/app/popovers/editor/app-color/app-color.scss
- studio/src/app/popovers/editor/app-color/app-color.tsx
- studio/src/app/utils/editor/target-element.tsx
- studio/src/components.d.ts
Move code color selection to color picker instead of in code options
> feat(#394): refactor code color design

- CHANGELOG.md
- README.md
- docs/CHANGELOG.md
- docs/docs/components/app-components-inline-editor/app-components-inline-editor.md
- docs/package-lock.json
- docs/package.json
- docs/src/app/pages/docs/components/app-components-highlight-code/app-components-highlight-code.tsx
- docs/src/app/pages/docs/components/app-components-inline-editor/app-components-inline-editor.tsx
- webcomponents/color/CHANGELOG.md
- webcomponents/color/package-lock.json
- webcomponents/color/package.json
- webcomponents/inline-editor/CHANGELOG.md
- webcomponents/inline-editor/package-lock.json
- webcomponents/inline-editor/package.json
- webcomponents/inline-editor/src/components/inline-editor/deckdeckgo-inline-editor.tsx
- webcomponents/inline-editor/src/components/inline-editor/readme.md
Follow up https://github.com/deckgo/deckdeckgo/pull/528
> inline-editor: fix and release inline code palette

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/docs.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/pull_request_template.md
This is a first setup for #533.
> feature: add github templates

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- [ X] Docs have been  updated (for features)
Add some more elements to the list of potential affected parts in the templates for issues
- [X ] Documentation content changes
Issue Number: #533
> docs: add granularity to affected parts

- studio/src/global/theme/fonts.scss
> style: remove color strong

- studio/src/app/components/feed/app-feed/app-feed.tsx
> fix(a11y): add aria label for presentation links

- CHANGELOG.md
- cloud/CHANGELOG.md
- cloud/functions/package-lock.json
- cloud/functions/package.json
- cloud/functions/src/watch/info/info-deck-publish.ts
- cloud/functions/src/watch/watch-deck.ts
It might happens that users are trying out studio and are even trying out to publish their presentations. For example publishing a presentation with one slide containing dummy text like "Test".
Such content should be moderated to not be displayed on the feed page of studio.
Therefore, each time a deck will be published, this new function will send me an email (containing title, id and link to the presentation).
> cloud: ping on publish

- remote/src/app/components/app-draw/app-draw.tsx
> feat(437): adding desynchronized hint to canvas

- studio/src/app/components/editor/actions/app-editor-actions/app-editor-actions.tsx
- studio/src/app/components/editor/actions/app-share-action/app-share-action.tsx
- studio/src/app/components/editor/app-share-deck/app-share-deck.tsx
- studio/src/app/components/editor/app-share-options/app-share-options.tsx
- studio/src/app/modals/editor/app-embed/app-embed.scss
- studio/src/app/modals/editor/app-embed/app-embed.tsx
- studio/src/app/services/editor/share/share.service.tsx
- studio/src/app/utils/editor/more-action.tsx
- studio/src/components.d.ts
- studio/src/global/theme/input.scss
> feat(#359): code embed

- studio/src/app/modals/editor/app-remote-connect/app-remote-connect.scss
- studio/src/app/modals/editor/app-remote-connect/app-remote-connect.tsx
> feat(#545): text position and size

- studio/src/app/components/landing/app-landing-content/app-landing-content.scss
- studio/src/app/components/landing/app-landing-content/app-landing-content.tsx
- studio/src/app/components/landing/app-landing-deck/app-landing-deck.scss
- studio/src/app/components/landing/app-landing-deck/app-landing-deck.tsx
- studio/src/app/components/landing/app-landing-footer/app-landing-footer.tsx
- studio/src/app/components/landing/app-landing/app-landing.scss
- studio/src/app/components/landing/app-landing/app-landing.tsx
- studio/src/app/pages/core/app-home/app-home.tsx
- studio/src/components.d.ts
> feat(#561): improve landing loading performance

- CHANGELOG.md
- docs/package-lock.json
- docs/package.json
- remote/package-lock.json
- remote/package.json
- studio/package-lock.json
- studio/package.json
- webcomponents/youtube/CHANGELOG.md
- webcomponents/youtube/package-lock.json
- webcomponents/youtube/package.json
- webcomponents/youtube/src/components/deckdeckgo-youtube.tsx
- webcomponents/youtube/src/index.html
If a Youtube video URL is provided as `embed` without containing `jsenableapi=1`, then it won't be possible to call `play` and `pause`. Therefore, test the url and add the parameter before creating the `iframe` in our YouTube component.
> feat: improve Youtube embed for play and pause

- webcomponents/social/package-lock.json
- webcomponents/social/package.json
- webcomponents/social/src/components/deckdeckgo-social.tsx
- webcomponents/youtube/package-lock.json
- webcomponents/youtube/package.json
- webcomponents/youtube/src/components/deckdeckgo-youtube.tsx
Both social and YouTube components are use by our slides, therefore, for declarative validation, they should implements the slide component interfaces
> feat: implements slides interfaces components

- studio/src/app/components/landing/app-landing-deck/app-landing-deck.scss
- studio/src/app/components/landing/app-landing-deck/app-landing-deck.tsx
> fix(#561): lazy load background image of deck landing

- studio/src/app/components/core/app-footer/app-footer.scss
- studio/src/app/components/core/app-menu/app-menu.scss
- studio/src/app/components/core/app-menu/app-menu.tsx
- studio/src/global/theme/menu.scss
> feat(#554): improve menu a11y

- studio/src/app/components/editor/app-editor-toolbar/app-editor-toolbar.tsx
- studio/src/app/pages/editor/app-editor/app-editor.tsx
- studio/src/components.d.ts
> fix(#536): on elements focus with Tab, swipe the slider if needed

- studio/src/app/components/core/app-navigation-actions/app-navigation-actions.tsx
> fix(#584): replace button padding with margin

- studio/src/app/components/core/app-footer/app-footer.scss
- studio/src/app/components/core/app-footer/app-footer.tsx
- studio/src/app/components/core/app-menu/app-menu.tsx
> feat(#588): remove deck from menu

- studio/src/app/handlers/editor/events/deck/deck-events.handler.tsx
> feat(#587): delete db attributes and background if empty

- infra/handler/app/Test.hs
- infra/handler/package.yaml
- infra/handler/src/DeckGo/Handler.hs
- infra/nix/sources.json
> Fix CSP and support fonts

- studio/src/app/components/landing/app-landing-deck/app-landing-deck.tsx
> fix: resize landing deck on navigation

- studio/src/app/components/core/app-menu/app-menu.scss
- studio/src/app/modals/editor/app-code-languages/app-code-languages.scss
- studio/src/app/modals/editor/app-code-languages/app-code-languages.tsx
- studio/src/app/popovers/editor/app-code/app-code.scss
- studio/src/app/popovers/editor/app-code/app-code.tsx
- studio/src/app/services/editor/prism/prism.service.tsx
- studio/src/components.d.ts
- studio/src/global/theme/searchbar.scss
> feat(#389): searchbar code languages

- studio/src/app/components/editor/app-share-deck/app-share-deck.tsx
> feat(#618): share to Hacker News

- CHANGELOG.md
- studio/package-lock.json
- studio/package.json
- studio/src/app/components/editor/actions/app-actions-editor/app-actions-editor.tsx
- studio/src/app/components/editor/actions/element/app-actions-element/app-actions-element.tsx
- studio/src/app/components/editor/app-image/app-image.tsx
- studio/src/app/components/editor/app-select-target-element/app-select-target-element.tsx
- studio/src/app/helpers/editor/image.helper.tsx
- studio/src/app/helpers/editor/shape.helper.tsx
- studio/src/app/popovers/editor/app-image-element/app-image-element.scss
- studio/src/app/popovers/editor/app-image-element/app-image-element.tsx
- studio/src/app/popovers/editor/app-shape/app-shape.tsx
- studio/src/app/utils/editor/image-action.utils.tsx
- studio/src/app/utils/editor/shape-action.tsx
- studio/src/app/utils/editor/target-element.tsx
- studio/src/components.d.ts
- utils/deck/CHANGELOG.md
- utils/deck/package-lock.json
- utils/deck/package.json
- utils/deck/styles/deckdeckgo-deck.css
Add images as shapes to the new slide aspect ratio
> feat(#610): images (stock photos, gif etc.) as shapes

- studio/src/app/components/core/app-navigation-actions/app-navigation-actions.scss
- studio/src/app/components/core/app-navigation-actions/app-navigation-actions.tsx
- studio/src/app/components/landing/app-landing-deck/app-landing-deck.tsx
> fix(#534): keyboard tab on homepage

- studio/src/app/components/core/app-navigation/app-navigation.scss
- studio/src/app/components/core/app-navigation/app-navigation.tsx
We, @nmattia and I, are now considering DeckDeckGo has being stable :)
> feat: remove label "Beta" in navigation bar

- studio/src/app/popovers/editor/app-create-slide/app-create-slide.scss
- studio/src/app/popovers/editor/app-create-slide/app-create-slide.tsx
Yet again another improvement of the design of the showcase of the templates
> feat: select template design

- webcomponents/drag-resize-rotate/README.md
> doc: Fix install instructions and doc link in drag-resize-rotate

- studio/src/app/pages/core/about/app-about/app-about.tsx
You can be may more proud of yourself. You're doing a great job out there. Let it reflect in your about page. 😉
> docs(studio): update about page

- studio/src/app/components/editor/app-image/app-image.tsx
- studio/src/app/components/editor/color/app-color-code/app-color-code.tsx
- studio/src/app/components/editor/color/app-color-qrcode/app-color-qrcode.tsx
- studio/src/app/components/editor/color/app-color-sides/app-color-sides.tsx
- studio/src/app/components/editor/color/app-color-text-background/app-color-text-background.tsx
- studio/src/app/components/feed/app-feed/app-feed.tsx
- studio/src/app/popovers/editor/slide/app-edit-slide-chart/app-edit-slide-chart.tsx
- studio/src/app/popovers/editor/slide/app-edit-slide-qrcode/app-edit-slide-qrcode.tsx
- studio/src/global/app.scss
- studio/src/global/theme/button.scss
Issue Number: https://github.com/deckgo/deckdeckgo/issues/665
> studio: text-transform: none for all buttons

- studio/src/assets/assets.json
New fonts are added.
Issue Number: https://github.com/deckgo/deckdeckgo/issues/660
> studio: added new selected fonts

- studio/src/app/pages/core/app-dashboard/app-dashboard.tsx
- studio/src/app/pages/core/app-settings/app-settings.tsx
- studio/src/global/theme/button.scss
- studio/src/global/theme/fonts.scss
This introduces the class `.app-button` so let a button look like a link (before ion-router-link).
Issue Number: #673
> fix(a11y): convert router-link to button for keyboard navigation

- webcomponents/youtube/src/components/deckdeckgo-youtube.scss
- webcomponents/youtube/src/components/deckdeckgo-youtube.tsx
youtube: smoother display transition
Issue Number: https://github.com/deckgo/deckdeckgo/issues/570
> youtube: smoother display transition

- webcomponents/inline-editor/src/components/inline-editor/deckdeckgo-inline-editor.scss
- webcomponents/inline-editor/src/components/inline-editor/deckdeckgo-inline-editor.tsx
- webcomponents/inline-editor/src/types/inline-editor/deckdeckgo-inline-editor-utils.tsx
- webcomponents/inline-editor/src/utils/enums.ts
Issue Number: https://github.com/deckgo/deckdeckgo/issues/680
> feat: text aligment in inline-editor

- studio/src/app/components/landing/app-landing-deck/app-landing-deck.tsx
> feat: add offline support to landing introduction

- utils/deck/styles/deckdeckgo-deck.css
Issue Number: https://github.com/deckgo/deckdeckgo/issues/679
> split vertical text alignment

- docs/docs/components/app-components-highlight-code/app-components-highlight-code.md
- webcomponents/highlight-code/src/components/highlight-code/deckdeckgo-highlight-code.scss
Issue Number: [707](https://github.com/deckgo/deckdeckgo/issues/707)
> highlight-code(#707) make code white-space a css variable

- studio/src/app/components/editor/app-image/app-image.tsx
- studio/src/app/components/editor/color/app-color-chart/app-color-chart.tsx
- studio/src/app/components/editor/color/app-color-code/app-color-code.tsx
- studio/src/app/popovers/editor/app-code/app-code.tsx
- studio/src/app/popovers/editor/app-math/app-math.tsx
- studio/src/app/popovers/editor/slide/app-edit-slide-author/app-edit-slide-author.tsx
- studio/src/app/popovers/editor/slide/app-edit-slide-chart/app-edit-slide-chart.tsx
- studio/src/global/theme/popover.scss
Improve a11y, makes options accessible more easily or more quickly
> feat(a11y): select as popover

- studio/src/app/components/editor/actions/element/app-actions-element/app-actions-element.tsx
- studio/src/app/components/editor/app-slot-type/app-slot-type.scss
- studio/src/app/components/editor/app-slot-type/app-slot-type.tsx
- studio/src/app/pages/editor/app-editor/app-editor.tsx
- studio/src/app/popovers/editor/app-create-slide/app-create-slide.scss
- studio/src/app/popovers/editor/app-create-slide/app-create-slide.tsx
- studio/src/app/popovers/editor/app-transform/app-transform.scss
- studio/src/app/popovers/editor/app-transform/app-transform.tsx
- studio/src/app/utils/editor/create-slides.utils.tsx
- studio/src/components.d.ts
> feat(#729): select elements before creating slide

- studio/src/app/components/editor/actions/deck/app-actions-deck/app-actions-deck.tsx
- studio/src/app/components/editor/app-select-target-element/app-select-target-element.tsx
- studio/src/app/components/editor/styles/deck/app-deck-fonts/app-deck-fonts.scss
- studio/src/app/components/editor/styles/deck/app-deck-fonts/app-deck-fonts.tsx
- studio/src/app/popovers/editor/style/app-deck-style/app-deck-style.tsx
- studio/src/app/utils/editor/target-element.tsx
- studio/src/components.d.ts
meanwhile also remove backdrop and keep popover open when user select a font style
> feat: group and improve fonts in deck style

- CHANGELOG.md
- docs/CHANGELOG.md
- docs/package-lock.json
- docs/package.json
- remote/CHANGELOG.md
- remote/package-lock.json
- remote/package.json
- studio/package-lock.json
- studio/package.json
- webcomponents/slides/qrcode/CHANGELOG.md
- webcomponents/slides/qrcode/package-lock.json
- webcomponents/slides/qrcode/package.json
- webcomponents/slides/qrcode/src/components/slide/deckdeckgo-slide-qrcode.tsx
- webcomponents/slides/qrcode/src/index.html
> fix(#743): slide qr code size calculation

- webcomponents/inline-editor/src/components.d.ts
- webcomponents/inline-editor/src/components/actions/style-actions/style-actions.tsx
- webcomponents/inline-editor/src/components/inline-editor/deckdeckgo-inline-editor.tsx
- webcomponents/inline-editor/src/utils/utils.tsx
Issue Number: https://github.com/deckgo/deckdeckgo/issues/710
> inline-editor: added feature strikethrough

- CHANGELOG.md
- docs/CHANGELOG.md
- docs/package-lock.json
- docs/package.json
- studio/package-lock.json
- studio/package.json
- webcomponents/inline-editor/CHANGELOG.md
- webcomponents/inline-editor/package-lock.json
- webcomponents/inline-editor/package.json
- webcomponents/inline-editor/src/components/actions/style-actions/style-actions.tsx
- webcomponents/inline-editor/src/components/inline-editor/deckdeckgo-inline-editor.tsx
- webcomponents/inline-editor/src/utils/utils.tsx
> feat(#710): release strikethrough

- studio/src/app/services/editor/publish/publish.service.tsx
Regex applied to /s not support in Firefox.
Closes #751
> fix(#751): clean notes on Firefox

- remote/src/app/components/app-notes/app-notes.scss
- remote/src/app/pages/app-remote/app-remote.scss
- remote/src/app/pages/app-remote/app-remote.tsx
Tested: FF ESR (68), FF 77, Chrome 83.
Issue Number: Problem with remote control layout in Firefox Mobile #752
I think refactored grid will make other changes easier.
I also changed proportions in landscape mode (2nd commit). The presentation was very squished with 50/50 proportions. I think this works better.
> Remote grid refactor

- cloud/functions/.prettierrc
- cloud/functions/package-lock.json
- cloud/functions/package.json
- cloud/functions/src/watch/screenshot/generate-deck-screenshot.ts
> cloud: social card not always generated in social cards

- studio/src/app/handlers/editor/events/deck/deck-events.handler.tsx
- studio/src/app/pages/editor/app-editor/app-editor.tsx
- studio/src/app/stores/busy.store.ts
race conditions since the migration to the store
> fix: code editable attribute was sometimes missing

- studio/src/app/components/editor/app-select-target-element/app-select-target-element.scss
- studio/src/app/components/editor/app-slot-type/app-slot-type.tsx
- studio/src/app/components/editor/styles/app-expansion-panel/app-expansion-panel.scss
- studio/src/app/components/editor/styles/element/app-reveal/app-reveal.tsx
- studio/src/app/popovers/editor/app-code/app-code.tsx
- studio/src/app/popovers/editor/app-create-slide/app-create-slide.scss
- studio/src/app/popovers/editor/app-create-slide/app-create-slide.tsx
- studio/src/app/popovers/editor/app-math/app-math.tsx
- studio/src/app/popovers/editor/app-shape/app-shape.scss
- studio/src/app/popovers/editor/app-shape/app-shape.tsx
- studio/src/global/theme/editor/editor-mixin.scss
- studio/src/global/theme/editor/editor-popover.scss
- studio/src/global/theme/list.scss
- studio/src/global/theme/popover.scss
- studio/src/global/theme/toolbar.scss
Makes clearer which options are grouped or not in  the popover options
> style: group card popover options

- docs/docs/slides/app-slide-author/app-slide-author.md
- docs/docs/slides/app-slides-concept/app-slides-concept.md
- docs/src/app/pages/docs/slides/app-slide-author/app-slide-author.tsx
- docs/src/app/pages/docs/slides/app-slides-concept/app-slides-concept.tsx
- remote/src/app/pages/app-remote/app-remote.tsx
- remote/src/app/pages/app-timer/app-timer.tsx
- studio/src/app/pages/core/about/app-opensource/app-opensource.tsx
- studio/src/app/pages/core/about/app-team/app-team.tsx
This fixes #812 
Issue Number: #812
> fix(a11y): correct implementation aria labels, improve copy

- studio/src/app/pages/core/about/app-team/app-team.tsx
> fix: social icons uri

- studio/src/app/components/enterprise/app-features/app-features.tsx
- studio/src/app/components/landing/app-landing-deck/app-landing-deck.tsx
Congatulations on releasing 'Enterprise' mode. Some small adjustments to its copy.
> fix: adjust copy enterprise

- studio/src/app/popovers/editor/app-create-slide/app-create-slide.tsx
> fix: unhandle and unexpected add slide

- studio/src/app/services/auth/auth.service.tsx
Log an error msg in the console in case the anonymous or registered authentication process fails.
Solves #827
> feat: log auth error the console

- studio/src/app/pages/core/about/app-services/app-services.tsx
> feat: display regions in services page

- webcomponents/core/src/components.d.ts
- webcomponents/core/src/components/deck/deckdeckgo-deck/deckdeckgo-deck.tsx
- webcomponents/core/src/index.html
> feat: deck auto-slide

- studio/src/app/components/editor/styles/element/app-align/app-border-radius.tsx
- studio/src/app/popovers/editor/style/app-element-style/app-element-style.tsx
- studio/src/components.d.ts
> Studio borderradius

- studio/src/app/components/editor/styles/element/app-align/app-letter-spacing.tsx
- studio/src/app/popovers/editor/style/app-element-style/app-element-style.tsx
- studio/src/components.d.ts
> Studio - Implemented letter spacing

- docs/docs/deck/app-deck-auto-slide/app-deck-auto-slide.md
- docs/src/app/app-root.tsx
- docs/src/app/pages/docs/deck/app-deck-auto-slide/app-deck-auto-slide.tsx
> add auto slide documentation

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/pull_request_template.md
- studio/src/app/services/palette/palette.service.tsx
Small improvement to keep our issues (more) clean.
> docs: improve github templates

- docs/src/app/pages/app-home/app-home.scss
- docs/src/app/pages/app-home/app-home.tsx
> fix(docs): align feature list correctly

- studio/src/app/components/editor/styles/element/app-align/app-box-shadow.tsx
- studio/src/app/utils/editor/color.utils.tsx
- studio/src/components.d.ts
> Studio - boxshadow initial vals + opacity fix

- webcomponents/color/src/components/color/deckdeckgo-color.scss
This PR just adds a focus state to the color picker to help with accessibility. 
Issue Number: #922
> bug(a11y): add focus state to color picker

- studio/src/app/components/editor/styles/deck/app-deck-header-footer/app-deck-header-footer.tsx
- studio/src/app/components/editor/styles/deck/app-deck-transition/app-deck-transition.tsx
- studio/src/app/components/editor/styles/element/app-color-code/app-color-code.tsx
- studio/src/app/components/editor/styles/element/app-image-style/app-image-style.tsx
- studio/src/app/popovers/editor/style/app-element-style/app-element-style.tsx
> refactor(styles): introduce optional chaining

- studio/src/app/components/core/app-random-gif/app-random-gif.tsx
- studio/src/app/components/dashboard/app-dashboard-deck-actions/app-dashboard-deck-actions.tsx
- studio/src/app/components/feed/card/app-feed-card/app-feed-card.tsx
- studio/src/app/pages/core/app-dashboard/app-dashboard.tsx
- studio/src/app/pages/core/app-poll/app-poll.tsx
> refactor: introduce optional chaining

- studio/src/app/components/dashboard/app-dashboard-deck-actions/app-dashboard-deck-actions.tsx
- studio/src/app/components/feed/card/app-feed-card/app-feed-card.tsx
- studio/src/app/pages/core/app-dashboard/app-dashboard.tsx
backwards compatibility, even though it should not be an issue, tests were ok.
> feat: optional chaining typesafe

- studio/src/app/services/core/environment/environment-config.tsx
- studio/src/app/services/editor/offline/offline.service.tsx
- studio/src/app/services/editor/publish/publish.service.tsx
- studio/src/app/services/editor/remote/remote.service.tsx
> refactor(services): introduce optional chaining

- studio/src/app/components/core/app-menu/app-menu.tsx
- studio/src/app/components/core/app-navigation-actions/app-navigation-actions.tsx
- studio/src/app/pages/core/app-dashboard/app-dashboard.tsx
- studio/src/app/pages/core/app-settings/app-settings.tsx
- studio/src/app/pages/editor/app-editor/app-editor.tsx
> refactor(sign-in): introduce optional chaining

- studio/src/app/components/editor/actions/deck/app-actions-deck/app-actions-deck.tsx
- studio/src/app/components/editor/actions/element/app-actions-element/app-actions-element.tsx
- studio/src/app/components/editor/app-image-columns/app-image-columns.tsx
- studio/src/app/components/editor/app-slot-type/app-slot-type.tsx
- studio/src/app/components/editor/publish/app-publish-edit/app-publish-edit.tsx
- studio/src/app/helpers/editor/editor.helper.tsx
- studio/src/app/helpers/editor/image.helper.tsx
- studio/src/app/pages/editor/app-editor/app-editor.tsx
- studio/src/app/popovers/editor/app-shape/app-shape.tsx
- studio/src/app/popovers/editor/remote/app-remote-request/app-remote-request.tsx
> refactor(editor): introduce optional chaining

- studio/src/app/stores/deck.store.ts
- studio/src/app/stores/user.store.ts
> refactor(store): introduce optional chaining

- studio/src/app/utils/core/share.utils.tsx
- studio/src/app/utils/editor/image-action.utils.tsx
- studio/src/app/utils/editor/list.utils.tsx
- studio/src/app/utils/editor/reveal-slot.utils.tsx
- studio/src/app/utils/editor/slot.utils.tsx
- studio/src/app/utils/editor/social.utils.tsx
> refactor(utils): introduce optional chaining

- studio/package.json
- studio/src/sw.js
> feat: updated studio to use workbox v5.x

- studio/src/app/components/editor/app-image-columns/app-image-columns.tsx
- studio/src/app/components/editor/styles/app-image/app-image.tsx
- studio/src/app/definitions/svg-waves.d.ts
- studio/src/app/helpers/editor/image.helper.tsx
- studio/src/app/helpers/editor/shape.helper.tsx
- studio/src/app/helpers/editor/svgWaves.helper.tsx
- studio/src/app/modals/editor/app-svg-waves/app-svg-waves.scss
- studio/src/app/modals/editor/app-svg-waves/app-svg-waves.tsx
- studio/src/app/services/editor/image-history/image-history.service.ts
- studio/src/app/utils/editor/edit-action.tsx
- studio/src/app/utils/editor/image-action.tsx
- studio/src/app/utils/editor/image-action.utils.tsx
- studio/src/app/utils/editor/svg-waves.utils.tsx
- studio/src/components.d.ts
PR is still work in progress, but available for review. it's my first time adding features, your review and suggestions will be very helpful, thank you!
TODO:
Issue Number: #874
> studio: svg waves for deck or slide background

- studio/src/app/utils/editor/firestore.utils.tsx
fix cleaning of `firebase.firestore.FieldValue.delete()`
> studio: fix clean persisted deck

- studio/src/app/components/editor/styles/app-color-text-background/app-color-text-background.tsx
- studio/src/app/components/editor/styles/element/app-box-shadow/app-box-shadow.tsx
- studio/src/app/components/editor/styles/element/app-color-code/app-color-code.tsx
- studio/src/app/components/editor/styles/element/app-color-word-cloud/app-color-word-cloud.tsx
- studio/src/app/components/editor/styles/slide/app-color-chart/app-color-chart.tsx
- studio/src/app/components/editor/styles/slide/app-color-qrcode/app-color-qrcode.tsx
- studio/src/app/components/editor/styles/slide/app-color-sides/app-color-sides.tsx
- studio/src/app/modals/editor/app-svg-waves/app-svg-waves.tsx
avoid multiple updates when color are selected as the event is propagated
> fix: color propagation and multiple updates

- docs/docs/components/app-components-word-cloud/app-components-word-cloud.md
- docs/src/app/app-root.tsx
- docs/src/app/pages/docs/components/app-components-word-cloud/app-components-word-cloud.tsx
- docs/src/components.d.ts
Documentation for word cloud component
Issue Number: #951
> docs: documentation for word cloud

- studio/src/app/components/editor/actions/app-breadcrumbs/app-breadcrumbs.tsx
- studio/src/app/components/editor/actions/footer/app-actions-editor/app-actions-editor.tsx
- studio/src/app/pages/editor/app-editor/app-editor.tsx
- studio/src/components.d.ts
I took the second approach you recommended and added the slide number as a State inside the app-editor and path it down to the breadcrumbs.
Issue Number: #966
> add the active slider number in footer breadcrumbs

- docs/docs/components/app-components-social/app-components-social.md
- webcomponents/social/src/components/deckdeckgo-social.e2e.ts
- webcomponents/social/src/components/deckdeckgo-social.tsx
- webcomponents/social/src/index.html
Issue Number: Fixes #959 , but introduces breaking changes to some medium profiles
> (fix) updates to new medium profile URL

- studio/src/app/pages/core/app-poll/app-poll.scss
- studio/src/app/pages/core/app-poll/app-poll.tsx
> feat: add a cancel button to take part to a new poll

- studio/src/app/components/editor/styles/app-color/app-color.scss
- studio/src/app/components/editor/styles/app-color/app-color.tsx
- studio/src/app/pages/editor/app-editor/app-editor.tsx
- studio/src/app/services/color/color.service.tsx
- studio/src/app/stores/color.store.ts
- studio/src/app/utils/editor/color.utils.tsx
Related to https://github.com/deckgo/deckdeckgo/issues/919#issuecomment-718211086
> color history with default palette

- studio/src/app/pages/editor/app-editor/app-editor.tsx
It makes things behave weirdly when button next / prev are used. Also it's surprising it terms of UX.
> fix: remove auto select slide

- remote/CHANGELOG.md
- remote/src/app/pages/app-remote/app-remote.scss
> fix: draw remote canvas position

- backend/package-lock.json
- remote/src/app/pages/app-remote/app-remote.scss
> play button position fixed

- studio/src/app/utils/editor/firestore.utils.tsx
- studio/src/app/utils/editor/offline.utils.tsx
> fix: clean offline slides

- studio/src/app/handlers/editor/events/deck/deck-events.handler.tsx
> feat: hide spellcheck in fullscreen presenting mode

- .github/workflows/backup.yml
avoid running this job in forked repo
> fix: scope github actions backup

- .github/workflows/site.yml
- site/gatsby-node.js
> feat: github action to deploy site

- site/src/components/landing/deck/landing-deck.module.scss
@nmattia almost forgot but done and live in 2'
"light grey instead of hidden"
> style: deck arrows navigation display on smaller device

- site/src/components/core/menu/menu.js
This PR adds a close button for the menu bar
Issue Number: #1047
> site: added menu close button

- infra/default.nix
This is a nice clean up of the nix code as well as formatting.
> Clean up nix code

- infra/default.nix
- infra/firebase-login/default.nix
- infra/firebase-login/shell.nix
- infra/google-key-updater/Main.hs
- infra/google-key-updater/default.nix
- infra/handler/default.nix
- infra/nix/sources.json
- infra/nix/sources.nix
- infra/unsplash-proxy/Main.hs
- infra/unsplash-proxy/default.nix
Format infra code and update starter
> Format infra code and update starter

- infra/default.nix
- infra/pgutil.nix
> infra: Add nixpkgs-fmt to shell

- studio/src/app/components/core/app-share-deck/app-share-deck.tsx
> #1090 - Added Telegram to list of share deck

- studio/src/app/components/editor/publish/app-publish-edit/app-publish-edit.tsx
> fix: edit description should not unlock title

- webcomponents/highlight-code/src/components/highlight-code/deckdeckgo-highlight-code.scss
This adds `line-height` as a configurable CSS property in the `highlight-code` component.
> add line height as customizable variable.

- studio/src/app/modals/editor/app-notes/app-notes.tsx
> fix: notes encoding on display

- studio/src/app/services/editor/offline/offline.service.ts
> feat: cache unique urls

- webcomponents/inline-editor/src/components.d.ts
- webcomponents/inline-editor/src/components/inline-editor/deckdeckgo-inline-editor.tsx
- webcomponents/inline-editor/src/components/inline-editor/readme.md
> feat: Expose displayTools method in inline-editor component publicly

- CHANGELOG.md
- webcomponents/drag-resize-rotate/CHANGELOG.md
- webcomponents/drag-resize-rotate/package-lock.json
- webcomponents/drag-resize-rotate/package.json
- webcomponents/drag-resize-rotate/src/components/deckdeckgo-drr.tsx
- webcomponents/drag-resize-rotate/src/index.html
> feat: drr toggle property on the fly

- studio/src/app/popovers/editor/app-slide-warning-info/app-slide-warning-info.scss
- studio/src/app/popovers/editor/app-slide-warning-info/app-slide-warning-info.tsx
- studio/src/assets/i18n/de.json
- studio/src/assets/i18n/en.json
- studio/src/assets/i18n/es.json
A small style change to make the action button a bit less predominant.
> style: deactivate low contrast warnings

- studio/src/app/popovers/core/app-user-menu/app-user-menu.tsx
-
- [X ] Bugfix
Issue Number: 1200
> fix: add "customization" and "templates" links to top right menu

- studio/src/global/theme/mixins/_dashboard.scss
> fix: broken grid style on wide screen

- studio/scripts/config.index.js
See https://twitter.com/daviddalbusco/status/1414626842686988289
> build: speed up boot time on the ic

- studio/src/app/services/auth/auth.service.ts
- studio/src/app/services/editor/publish/publish.service.ts
- studio/src/app/services/editor/sync/sync.service.ts
- studio/src/app/types/core/environment-config.ts
- studio/src/app/utils/core/environment.utils.ts
With the introduction of the offline mode, it should be possible to run it without any cloud providers, therefore the optional configuration.
> feat: firebase optional

- studio/src/app/components/core/app-navigation/app-navigation.tsx
- studio/src/app/components/core/app-spinner/app-spinner.scss
- studio/src/app/components/core/app-spinner/app-spinner.tsx
- studio/src/app/definitions/i18.d.ts
- studio/src/app/pages/editor/app-editor/app-editor.scss
- studio/src/app/pages/editor/app-editor/app-editor.tsx
- studio/src/app/stores/busy.store.ts
- studio/src/assets/i18n/de.json
- studio/src/assets/i18n/en.json
- studio/src/assets/i18n/es.json
> feat: spinner loading until deck is loaded

- studio/canisters/decks/decks.mo
- studio/canisters/decks/decks.store.mo
- studio/canisters/slides/slides.mo
- studio/src/app/canisters/slides/slides.did
- studio/src/app/canisters/slides/slides.did.d.ts
- studio/src/app/canisters/slides/slides.utils.did.js
rever, each canister has its own principal
open question -> https://forum.dfinity.org/t/check-if-function-is-called-from-another-canister/6345
> revert: admin privilege that does not work

- studio/canisters/deck/deck.mo
https://forum.dfinity.org/t/class-actor-constructor-variables-stable/6399
> fix: stable deck canister owner

- studio/canister_ids.json
I kind of corrupted previous decks canister 😅
https://forum.dfinity.org/t/map-and-buckets-example-candid-definition-not-generated/6386/3?u=peterparker
> feat: update decks mgmt canister id

- studio/src/app/components/editor/actions/element/app-actions-element/app-actions-element.scss
- studio/src/app/components/editor/actions/footer/app-actions-editor/app-actions-editor.tsx
- studio/src/app/pages/editor/app-editor/app-editor.tsx
> feat: select deck with additional click on editor

- CHANGELOG.md
- package-lock.json
- webcomponents/highlight-code/CHANGELOG.md
- webcomponents/highlight-code/package.json
- webcomponents/highlight-code/src/components/highlight-code/deckdeckgo-highlight-code.tsx
- webcomponents/highlight-code/src/index.html
> fix: higlight code sort required languages scripts first

- CHANGELOG.md
- webcomponents/highlight-code/CHANGELOG.md
- webcomponents/highlight-code/package.json
- webcomponents/highlight-code/src/components/highlight-code/deckdeckgo-highlight-code.tsx
> fix: clean zero width spaces on copy

- canisters/src/manager/bucket.store.mo
- canisters/src/manager/bucket.types.mo
- canisters/src/manager/manager.mo
- canisters/src/storage/storage.store.mo
- canisters/src/utils/canister.utils.mo
- providers/ic/src/canisters/manager/manager.did
- providers/ic/src/canisters/manager/manager.did.d.ts
- providers/ic/src/canisters/manager/manager.utils.did.js
- providers/ic/src/providers/auth/auth.ic.ts
- providers/ic/src/providers/publish/publish.ic.ts
- providers/ic/src/providers/storage/storage.ic.ts
- providers/ic/src/providers/sync/sync.ic.ts
- providers/ic/src/utils/data.utils.ts
- providers/ic/src/utils/manager.utils.ts
- providers/ic/src/utils/publish.deck.utils.ts
- providers/ic/src/utils/publish.overview.utils.ts
- providers/ic/src/utils/publish.resources.utils.ts
- providers/ic/src/utils/publish.utils.ts
- providers/ic/src/utils/storage.utils.ts
- providers/ic/src/utils/sync.storage.utils.ts
- providers/ic/src/workers/sync.ic.worker.ts
- providers/ic/src/workers/user.ic.worker.ts
- studio/src/app/modals/core/app-user-delete/app-user-delete.tsx
- studio/src/app/pages/core/settings/app-profile/app-profile.tsx
- studio/src/assets/i18n/de.json
- studio/src/assets/i18n/en.json
- studio/src/assets/i18n/es.json
- studio/src/assets/i18n/nl.json
It can take up to 30 seconds until a bucket is created. Therefore better handle such period time so that if the user reload the browser, no new request of bucket creation will be performed until the original bucket creation is successfully done
> feat: better handle bucket creation

- providers/ic/src/providers/storage/storage.ic.ts
- studio/src/app/components/core/app-dashboard-actions/app-dashboard-actions.tsx
- studio/src/app/utils/core/dashboard.utils.ts
Update doc or deck delete, if it has been published, the published file should be deleted too.
> feat: delete published content

- site/src/themes/variables.scss
- studio/src/global/theme/variables.scss
> style: fix contrasting color

- docs/src/stories/templates/Poll.stories.js
> fix: Docs poll link
