- src/components/pager/deckdeckgo-pager/deckdeckgo-pager.scss
- src/components/slides/deckdeckgo-slide.scss
- src/components/slides/deckdeckgo-slide.tsx
Adds transition for `stroke-dasharray` for smoother progress bar
Adds default transition for `reveal` items, allows customization through two new CSS properties.
`--slide-reveal-transform` controls the reveal item's transform property before being revealed.
`--slide-reveal-duration` controls the duration of the reveal animation
> Add pager and reveal transitions

- src/components.d.ts
- src/components/slides/deckdeckgo-slide-youtube/deckdeckgo-slide-youtube.tsx
- src/index.html
Adds `@Method() toggle` to the `<deckgo-slide-youtube>` component, which alternates between `play` and `pause` states. 
TODO: post a message from the YouTube iFrame when the video is played/paused, so that `<deckgo-slide-youtube>` keeps an internal `@State() isPlaying` in sync with the video. Currently this implementation only works if `play`, `pause`, or `toggle` are called programmatically.
> feat(youtube): add toggle method

- infra/default.nix
- infra/dynamo.tf
- infra/handler/app/Handler.hs
- infra/handler/app/Test.hs
- infra/handler/package.yaml
- infra/handler/src/DeckGo/Handler.hs
- infra/lambda.tf
> handler: unique firebase uid and fix del/put

- infra/handler/app/Test.hs
- infra/handler/src/DeckGo/Handler.hs
> Add attributes to decks

- infra/handler/app/Test.hs
- infra/handler/src/DeckGo/Handler.hs
fixes #81 
fixes #92 
* Make deck attributes optional
* Make slide content optional
* Protect all slide APIs
> Update handle API

- infra/handler/app/Test.hs
- infra/handler/src/DeckGo/Handler.hs
Verify the identity of the user on
* PUT users
* DELETE users
* GET decks
* GET decks/<deck-id>
* POST decks
* PUT decks/<deck-id>
> Run auth checks on some APIs

- infra/handler/app/Test.hs
- infra/handler/src/DeckGo/Handler.hs
fixes #104 .
_May_ address `actions` later on.
> Background

- docs/docs/components/app-components-highlight-code/app-components-highlight-code.md
- docs/src/app/pages/app-home/app-home.scss
- docs/src/global/theme/code.scss
- webcomponents/highlight-code/src/components.d.ts
- webcomponents/highlight-code/src/components/highlight-code/deckdeckgo-highlight-code.scss
- webcomponents/highlight-code/src/components/highlight-code/deckdeckgo-highlight-code.tsx
- webcomponents/highlight-code/src/components/highlight-code/readme.md
- webcomponents/highlight-code/src/index.html
> Add line numbers to highlight code

- webcomponents/core/src/components.d.ts
- webcomponents/core/src/components/slides/deckgo-slide-countdown/deckdeckgo-slide-countdown.scss
- webcomponents/core/src/components/slides/deckgo-slide-countdown/deckgo-slide-countdown.tsx
- webcomponents/core/src/index.html
This commit adds ```deckgo-slide-countdown``` web core slide component.
Please see https://github.com/deckgo/deckdeckgo/issues/45
Usages:
```
<deckgo-slide-countdown hours="0" minutes="0" seconds="5">
<h1 slot="title">My presentation will start in</h1>
</deckgo-slide-countdown>
```
Exposed public method on the HTML element:
```
start() - To start the countdown.
stop() - To stop the countdown.
```
Exposed CSS custom properties:
```
--countdown-base-size : Initial component base size. 
--clock-background-color : Clock's background color
--clock-foreground-color : Clock's digits' color.
```
> Added deckgo-slide-countdown slide web core component

- docs/CHANGELOG.md
- docs/src/app/app-root.tsx
- docs/src/global/theme/menu.scss
related to https://github.com/deckgo/deckdeckgo/issues/59
> feat(#59): remove ion-split-pane in order to be able to prerender the documentation

- studio/src/app/components/core/app-navigation/app-navigation.scss
- studio/src/app/components/core/app-navigation/app-navigation.tsx
> feat(#248): display deck name in title while editing a presentation

- studio/src/app/components/editor/publish/app-publish-edit/app-publish-edit.tsx
> feat(#256): remove debounce when entering tags and prevent enter

- studio/src/app/components/core/app-menu/app-menu.tsx
- studio/src/app/services/data/deck/deck.service.tsx
> feat(#249): sort deck by updated dates rather than created

- studio/src/app/pages/editor/app-editor/app-editor.tsx
> feat(#263): when switching to fullscreen mode, presenting mode per default not the edition mode

- CHANGELOG.md
- studio/package-lock.json
- studio/package.json
- webcomponents/inline-editor/CHANGELOG.md
- webcomponents/inline-editor/package-lock.json
- webcomponents/inline-editor/package.json
- webcomponents/inline-editor/src/components/inline-editor/deckdeckgo-inline-editor.scss
- webcomponents/inline-editor/src/components/inline-editor/deckdeckgo-inline-editor.tsx
- webcomponents/utils/CHANGELOG.md
- webcomponents/utils/package-lock.json
- webcomponents/utils/package.json
- webcomponents/utils/src/utils/deckdeckgo-utils.ts
> inline-editor: debounce to solve tools appearing on continuing selection

- studio/src/app/components/core/app-delete-deck-action/app-delete-deck-action.tsx
- studio/src/app/components/core/app-menu/app-menu.tsx
- studio/src/app/pages/core/app-dashboard/app-dashboard.scss
- studio/src/app/pages/core/app-dashboard/app-dashboard.tsx
- studio/src/components.d.ts
> Propagate deck delete to menu and dashboard

- studio/src/app/popovers/editor/app-code/app-code.tsx
> feat(#353): use color picker to select code's colors

- infra/handler/app/Test.hs
- infra/handler/src/DeckGo/Handler.hs
> infra: render presentation description

- webcomponents/color/src/components/color/deckdeckgo-color.scss
This PR resolves #390. The overflow property of the container of the color picker Web Component has been set as visible
> Set color-container class overflow to visible - resolves #390

- webcomponents/core/src/components/deck/deckdeckgo-deck/deckdeckgo-deck.tsx
Resolves issue #388
- Pressing J will go to the next slide
- Pressing K will go to the previous slide
Made it easy to insert other keys when required such as P and N for Emac/other users
Not sure if there's any tests that need to be created, quite new to contributing. Please let me know otherwise.
> Update keyboard assist to support Vim keybindings

- studio/src/app/components/feed/card/app-feed-card/app-feed-card.scss
Hid the title from all the cards present in the main feed. Slide tags are now displayed for all slides on the main feed.
Verified that the changes work as expected on the local build.
Closes #371
> Studio: display tags and hide title on cards in the main feed

- CHANGELOG.md
- studio/package-lock.json
- studio/package.json
- webcomponents/slides/qrcode/CHANGELOG.md
- webcomponents/slides/qrcode/package-lock.json
- webcomponents/slides/qrcode/package.json
- webcomponents/slides/qrcode/src/components/slide/deckdeckgo-slide-qrcode.tsx
In the editor (studio), on Android devices, when use open the popover to select new slides, the QR code is displayed to big as it was set to a 100% width. Inheriting solve the issue.
> fix: slide qrcode default width

- webcomponents/slides/split/src/components.d.ts
- webcomponents/slides/split/src/components/slide/deckdeckgo-slide-split.scss
- webcomponents/slides/split/src/components/slide/deckdeckgo-slide-split.tsx
- webcomponents/slides/split/src/index.html
Summary:
- Add Prop() `vertical` to DeckdeckgoSlideSplit
- Append attribute `-vertical` to slide classes `deckgo-slide` and `deckgo-slide-split`
- Add and extend `deckgo-slide-vertical` and `deckgo-slide-split-vertical` styles:
- `deckgo-slide-vertical`
- flex-flow is `column wrap`
- height is slide height - bottom paddings * 2: `calc(var(--slide-height) - (2 * var(--slide-split-padding-bottom, var(--slide-padding-bottom-default))))`
- `deckgo-slide-split-vertical`
- width is slide width - end & start paddings: `calc(var(--slide-width) - (var(--slide-split-padding-end, var(--slide-padding-end-default))) - (var(--slide-split-padding-start, var(--slide-padding-start-default))));`
Closes #372 🚀
> Add basic vertical split functionality

- webcomponents/highlight-code/src/components/highlight-code/deckdeckgo-highlight-code.tsx
- webcomponents/highlight-code/src/index.html
Fixes #423 Wrap code in a div when line nubmers are turned off to ensure correct highlighting
> fix(#423): fix wrong code highlight when line numbers are off

- remote/src/app/components/app-draw/app-draw.tsx
- webcomponents/remote/src/components/deckdeckgo-remote/deckdeckgo-remote.tsx
- webcomponents/remote/src/index.html
Create Interface for drawables
Abstract x/y to point
Drawables know how to draw themselfes
Save currently Drawing element at last position in array and change on move
Clear Canvas and draw whole array at once
> feat(#66): draw multiple circles

- webcomponents/core/src/components/deck/deckdeckgo-deck/deckdeckgo-deck.tsx
For now, deckdeckgo-deck only supports arrow keys and k/j for moving to previous/next slide.
As some remote controlers (actually, mine) send PageUp/PageDown, adding this two keys permit to use those.
I also fixed a typing issue BTW as it was breaking the build.
FYI: I need it because during a long session with demos (3 hours long in my case), or when you are stuck behind a desk/screen for other reasons (e.g. camera), using a smartphone as a remote controller is way less convenient than a small remote controller.
> Feat: PageUp/PageDown

- studio/src/app/services/data/feed/feed.service.tsx
Let's see but I think both in terms of performances as in terms of costs we are able to fetch more cards on each steps (of the infinite scroll) on the main feed.
Instead of 10 cards (aka 10 presentations) at a time, let's try to fetch 20.
As the cards are randomized in the feed, this is a bit more user friendly for both user browsing (almost same performance but more information) as for publisher because there is then more chances that their presentations would appears at the top of the list more often.
P.S.: We could always rollback easily to 10 again if needed.
> feat: fetch more cards on the main feed (each steps)

- docs/docs/slides/app-slide-author/app-slide-author.md
Minor grammar fixes throughout page. 
line 37:
Original sentence is more complicated then it needs to be.
So I simplified the sentence, also changed 'could' to 'should' as the template is already installed so you should skip the installation. The word 'could' implies that you can choose.
line 39
Made the sentence easier to understand.
Line 94:
Removed 'both' as you refer to three slots not two. Made the rest of the sentence more clear my splitting it into two sentences, also fixed grammar.
> Improved grammar in app-slide-author.md

- docs/docs/introduction/app-installation/app-installation.md
Line 3: 
Removed 'I' to make sentence more formal. Rearranged sentence to only use on 'and'.
line 7:
Split sentence into two, as the first part of the sentence is about using it via a CDN and the second part is about how to do that. 
Line 11:
Last part of sentence was grammatically incorrect and difficult to understand. Made a new sentence for it and re-worded it for better understanding.
> Text improvement to app-installation.md

- CHANGELOG.md
- docs/docs/slides/app-slide-poll/app-slide-poll.md
- docs/docs/slides/app-slides-concept/app-slides-concept.md
- docs/package-lock.json
- docs/package.json
- docs/src/app/pages/docs/slides/app-slide-poll/app-slide-poll.tsx
- docs/src/app/pages/docs/slides/app-slides-concept/app-slides-concept.tsx
- remote/package-lock.json
- remote/package.json
- studio/package-lock.json
- studio/package.json
- studio/src/app/utils/editor/create-slides.utils.tsx
- studio/src/global/app.ts
- webcomponents/slides/poll/CHANGELOG.md
- webcomponents/slides/poll/package-lock.json
- webcomponents/slides/poll/package.json
- webcomponents/slides/poll/src/components/slide/deckdeckgo-slide-poll.e2e.ts
- webcomponents/slides/poll/src/components/slide/deckdeckgo-slide-poll.tsx
- webcomponents/slides/poll/src/components/slide/readme.md
- webcomponents/slides/poll/src/index.html
Use `deckdeckgo.com/poll` instead of `poll.deckdeckgo.com`
> feat: firebase subdomain can't be redirect to path

- studio/src/app/popovers/core/app-user-menu/app-user-menu.tsx
- studio/src/app/popovers/editor/actions/app-more-actions/app-more-actions.tsx
- studio/src/app/popovers/editor/actions/app-more-share-options/app-more-share-options.tsx
- studio/src/app/popovers/editor/app-code/app-code.tsx
- studio/src/app/popovers/editor/app-color/app-color.tsx
- studio/src/app/popovers/editor/app-create-slide/app-create-slide.tsx
- studio/src/app/popovers/editor/app-element-delete/app-element-delete.tsx
- studio/src/app/popovers/editor/app-fullscreen-info/app-fullscreen-info.tsx
- studio/src/app/popovers/editor/app-get-help/app-get-help.tsx
- studio/src/app/popovers/editor/app-image/app-image.tsx
- studio/src/app/popovers/editor/app-reveal/app-reveal.tsx
- studio/src/app/popovers/editor/app-slot-type/app-slot-type.tsx
- studio/src/app/popovers/editor/slide/app-edit-slide/app-edit-slide.tsx
popover are HTMLIonPopoverElement not HTMLIonModalElement (even if both are inheriting same definitions)
> fix: typing HTMLIonPopoverElement

- CHANGELOG.md
- webcomponents/lazy-img/CHANGELOG.md
- webcomponents/lazy-img/package-lock.json
- webcomponents/lazy-img/package.json
- webcomponents/lazy-img/src/components/lazy-img/deckdeckgo-lazy-img.tsx
- webcomponents/lazy-img/src/index.html
Svg weren't displayed anymore as the detection of loaded was not correctly fully implemented.
> lazy-img: fix lazy img svg

- studio/src/index.html
I am not sure if this is done on purpose, but all of the other URLs are already linking to deckdeckgo.com without `beta.` in front. If done on purpose, this PR can be deleted.
> refactor: remove beta from urls

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/docs.md
- .github/ISSUE_TEMPLATE/feature.md
A lot of the sentences is just a guideline for people to provide information, therefore I put them as commented text. Next to that, the heading changes will result in better scanning, since they stand more out than the previous headings: almost the same size as normal text.
> docs: improve github templates

- studio/src/app/components/editor/actions/deck/app-actions-deck/app-actions-deck.tsx
- studio/src/app/components/editor/actions/element/app-actions-element/app-actions-element.tsx
- studio/src/global/theme/popover.scss
Backdrops in the editor, when it goes to editing, were a bit unpractical specially when it comes to colors as the selected color were applied behind a backdrop/shadow.
Removing the backdrops and adding a small box-shadow instead makes things more clear I think.
> feat: remove editor popover backdrops

- webcomponents/drag-resize-rotate/src/components/deckdeckgo-drr.scss
Fix content sizing of the drag, resize and rotate component in Firefox
> fix(#610): content sizing fit in Firefox

- webcomponents/drag-resize-rotate/src/components/deckdeckgo-drr.tsx
Fix jump position of the drag, resize and rotate component in Safari
> fix(#610): resize component in Safari ("no jump")

- studio/src/app/pages/editor/app-editor/app-editor.scss
- studio/src/app/popovers/editor/app-create-slide/app-create-slide.scss
- studio/src/app/popovers/editor/app-create-slide/app-create-slide.tsx
- studio/src/global/theme/editor/editor-fullscreen.scss
- add a md box-shadow around the edited deck (if not fullscreen and ready)
- improve template picker style
> feat: box-shadow for the deck

- remote/src/app/components/app-draw/app-draw.tsx
To be merged for/on next release
> feat(#625): unleash arrows in remote control

- webcomponents/drag-resize-rotate/src/components/deckdeckgo-drr.tsx
Calculate center for element in a way that remains correct for different rotation values, aspect ratios of element, etc.
> Fix #655: Calculate center for element correctly

- .github/workflows/cloud.yml
- .github/workflows/remote.yml
Deploy remote and cloud automatically with GitHub Actions only on releases (no more "push master")
> feat(#507): deploy cloud and remote to firebase only on releases

- CHANGELOG.md
- remote/package-lock.json
- remote/package.json
- studio/package-lock.json
- studio/package.json
- utils/deck/CHANGELOG.md
- utils/deck/package-lock.json
- utils/deck/package.json
- utils/deck/styles/deck/deck.scss
- utils/deck/styles/deck/fonts.scss
If styling was applied as content of a column in the split slide, then the alignment was not preserver (everything was aligned left because of display flex-direction column)
> fix: alignment fonts in split template

- studio/src/app/components/feed/card/app-feed-card/app-feed-card.scss
- studio/src/app/components/feed/card/app-feed-card/app-feed-card.tsx
Applying the right height on load without being glitchy and fixing the display of the author which was misalignated
> fix: preserve card and image ratio on feed

- studio/src/sw.js
Before this PR, if I go offline with the editor, turn off the wifi and refresh the browser's url or close Chrome and try to type the all url of my edited presentation (https://deckdeckgo.com/editor/:id) then it failed and displayed a 404.
With the help of this PR, the `/editor/:id/` path is cached with the help of a network first strategy and it solves the issue.
Note that in any case, the presentation still remains accessible through the root and navigation components (buttons).
> fix: support offline access to the editor directly with the browser's url

- studio/src/app/components/landing/app-landing-deck/app-landing-deck.tsx
Grammatical error from homepage: https://deckdeckgo.com/ -- slide number 4
Original text: 
> Integrate easily Youtube video.
Proposed change: 
> Easily integrate Youtube video.
---
_no functional changes_
> Fix grammar mistake on app-landing-deck.tsx

- infra/handler/app/Test.hs
- infra/handler/src/DeckGo/Handler.hs
This updates the API to read "header" and "footer" fields with are added
as `div`s with `slot = header` attributes.
> infra: Read and inject header and footer

- studio/src/app/services/data/deck/deck.offline.service.tsx
- studio/src/app/services/data/deck/deck.online.service.tsx
- studio/src/app/services/data/slide/slide.offline.service.tsx
- studio/src/app/services/editor/offline/offline.service.tsx
- studio/src/app/utils/editor/firestore.utils.tsx
- studio/src/app/utils/editor/offline.utils.tsx
Spare the Firestore.get we introduced yesterday (see [commit](https://github.com/deckgo/deckdeckgo/commit/a26c3f05d8369710050503f731390aa656381bac))
> feat: recursively clean Firestore FieldValue.delete

- studio/src/app/pages/core/app-settings/app-settings.tsx
It had side effect if user would change its avatar or custom logo more than once
> fix: componentdidload might be triggered twice with prerendering

- studio/src/app/components/core/app-footer/app-footer.tsx
- studio/src/app/components/editor/publish/app-publish-done/app-publish-done.tsx
- studio/src/app/components/feed/app-feed/app-feed.tsx
- studio/src/app/components/feed/app-popular/app-popular.tsx
- studio/src/app/modals/editor/app-playground/app-playground.tsx
- studio/src/app/pages/core/about/app-contact/app-contact.tsx
- studio/src/app/pages/core/about/app-faq/app-faq.tsx
- studio/src/app/pages/core/about/app-opensource/app-opensource.tsx
- studio/src/app/pages/core/about/app-services/app-services.tsx
- studio/src/app/pages/core/about/app-team/app-team.tsx
- studio/src/app/popovers/editor/app-get-help/app-get-help.tsx
Please check if your PR fulfils the following requirements:
I added both `noopener` and `noreferrer` to as many outgoing links as I could find. Some links to DeckDeckGo I **did not** change. This fixes #815 
Issue Number: #815
> refactor: add rel to links

- docs/docs/components/app-components-color/app-components-color.md
- webcomponents/color/src/components/color/deckdeckgo-color.tsx
> feat(style) allow container to be access via part

- studio/src/app/components/editor/app-image-columns/app-image-columns.tsx
- studio/src/app/pages/core/about/app-press/app-press.tsx
- studio/src/app/pages/core/about/app-remote/app-remote.tsx
- studio/src/app/popovers/editor/app-get-help/app-get-help.tsx
- studio/src/app/popovers/editor/remote/app-remote-connect/app-remote-connect.tsx
> chore: add rel to links

- studio/src/global/theme/editor/editor-fullscreen.scss
"Click to edit..." hidden in fullscreen mode if the deck is `.idle`
> fix: hide placeholder in fullscreen mode if idle

- cloud/functions/src/model/data/task.ts
- cloud/functions/src/request/publish/schedule-publish-task.ts
- cloud/functions/src/watch/publish/publish.ts
API first then GitHub (currently as we crawl the content from the published deck)
> fix: sequential publish

- docs/docs/components/app-components-highlight-code/app-components-highlight-code.md
- webcomponents/highlight-code/src/components/highlight-code/deckdeckgo-highlight-code.scss
- webcomponents/highlight-code/src/index.html
* It appears there are no tests for the `highlight-code` module
I opened the issue on the https://github.com/deckgo/gatsby-remark-highlight-code project due in part to having no idea where this code actually lived. A big thank you to @peterpeterparker for directing me over here!
Issue Number: https://github.com/deckgo/gatsby-remark-highlight-code/issues/21
For the example, I copied the `<h1>Without line numbers</h1>` example. The Github diff is being silly and showing my added changes above my `<h1>Without dots</h1>` when I actually added code below that. Also open to changing the content of the example if not as much is needed.
> Added the ability to toggle the Carbon toolbar and adjust the margin

- studio/src/app/app-root.tsx
- studio/src/app/components/editor/styles/app-color-text-background/app-color-text-background.tsx
- studio/src/app/components/editor/styles/element/app-color-code/app-color-code.tsx
- studio/src/app/components/editor/styles/slide/app-color-chart/app-color-chart.tsx
- studio/src/app/components/editor/styles/slide/app-color-qrcode/app-color-qrcode.tsx
- studio/src/app/components/editor/styles/slide/app-color-sides/app-color-sides.tsx
- studio/src/app/helpers/editor/palette.helper.ts
- studio/src/app/services/palette/palette.service.tsx
- studio/src/app/stores/palette.store.ts
This PR adds support for backing up changes made in custom-colors for the `deckgo-color`-component.
The backed up palette is stored in indexDB and initialized from that same store with the help of a paletteService
Issue Number: #902
> Saved previously used palette

- studio/src/app/components/editor/actions/app-actions-editor/app-actions-editor.scss
- studio/src/app/components/editor/actions/app-actions-editor/app-actions-editor.tsx
- studio/src/app/pages/editor/app-editor/app-editor.tsx
- utils/utils/src/utils/utils.ts
This PR sets a default for how th editor-panel is displayed while in fullscreen mode.
The panel is displayed with a lower opacity and without text when in fullscreen mode:
But as soon as the user hovers over the menu it will transition back to normal.
I also noticed that the helperfunction for checking if the device was in fullscreen mode didn't work for my device.
I debugged and implemented another way (which I think is safer) to check if the device is in fullscreen mode.
Issue Number: #901
> Default minimized editor-panel in fullscreen mode

- studio/src/app/components/editor/styles/deck/app-deck-fonts/app-deck-fonts.scss
Overflow of font item container fixed by adding hidden property for overflow.
Issue Number: #882
> add: overflow hidden for font item

- studio/src/app/components/editor/styles/app-color/app-color.scss
I think we might need to change more items so that they are visually seen focussed.
I used the same color as the outline color for title/subtitle in the first slide. Feel free to let me know which color to choose.
Issue Number: #997
> fix(a11y): show border when colors are focused by keyboard

- studio/src/app/components/editor/styles/app-color/app-color.scss
It will improve and standardize the focusing with keyboard of the font color selection.
**GIF of before state**
**GIF of after state**
Related to #998
> fix(a11y): improve font color focus state

- webcomponents/markdown/src/components/workers/utils/markdown-img.utils.ts
- webcomponents/markdown/src/index.html
- [ 👎 ] Tests for the changes have been added (for bug fixes / features)
- [ 👎 ] Docs have been added / updated (for bug fixes / features)
Updated the functionality of the of the markdown worker to look for width and height for images. If width and height exists then it will add those measurements to the deck deck go img and return. 
- [ X] Feature
Issue Number: 1007
> enhancement(markdown): updating markdown worker to identify width and height

- infra/default.nix
- infra/firebase-login/default.nix
- infra/firebase-login/nix/default.nix
- infra/firebase-login/nix/packages.nix
- infra/firebase-login/shell.nix
- infra/firebase-login/src/Servant/Auth/Firebase.hs
- infra/google-key-updater/default.nix
- infra/handler/app/Test.hs
- infra/handler/default.nix
- infra/handler/package.yaml
- infra/handler/src/DeckGo/Handler.hs
- infra/nix/default.nix
- infra/nix/sources.json
- infra/unsplash-proxy/Main.hs
- infra/unsplash-proxy/default.nix
This drops `static-haskell-nix` and `callCabal2nix`, making our setup
much simpler. This also includes a pretty big jump forward in terms of
Haskell deps.
> infra: drop static-haskell-nix and update nixpkgs

- studio/scripts/i18n.types.js
- studio/src/app/app-root.tsx
- studio/src/app/definitions/i18.d.ts
- studio/src/app/definitions/languages.d.ts
- studio/src/app/pages/core/settings/app-customization/app-customization.tsx
- studio/src/app/services/lang/lang.service.ts
- studio/src/app/stores/i18n.store.ts
> feat: toggle lang and detection

- .github/FUNDING.yml
Displays the sponsorship button linked with our newly created open collective.
> chore: add open collective sponsor

- webcomponents/highlight-code/src/components/highlight-code/deckdeckgo-highlight-code.scss
- webcomponents/highlight-code/src/components/highlight-code/readme.md
> style: add `width` and `height` CSS variables for the shadowed code block

- studio/src/app/components/editor/slide/app-slide-warning/app-slide-warning.tsx
- studio/src/app/definitions/i18.d.ts
- studio/src/app/pages/core/settings/app-customization/app-customization.tsx
- studio/src/app/popovers/editor/app-slide-warning-info/app-slide-warning-info.tsx
- studio/src/app/services/settings/settings.service.ts
- studio/src/app/stores/settings.store.ts
- studio/src/app/types/core/settings.ts
- studio/src/assets/i18n/de.json
- studio/src/assets/i18n/en.json
- studio/src/assets/i18n/es.json
- studio/src/components.d.ts
Issue Number: #1064
Dismiss Low Contrast Warning in app-slide-warning and app-slide-warning-info
I added a new Button to the dialog that informs the user about low contrast on their slides (in app-slide-warning-info.tsx).
The Button closes the dialog and emits and event "deactivateContrastWarning", which is listened to in app-slide-warning.tsx
In app-slide-warning.tsx I added a State property "checkLowContrast" which is a boolean and defaults to `true`
When "deactivateContrastWarning" is caught in app-slide-warning.tsx, this.checkLowContrast will be set to `false`
I did not implement something in "settings > customization" yet, to activate contrast warnings again.
I only tested …
> Adds button to deactivate low contrast warnings

- studio/src/app/components/editor/actions/element/app-actions-element/app-actions-element.tsx
We have to limit, at least for now, the length of the query when publishing to the API, therefore we should avoid users pasting bas64 images in the content
Likewise, by pasting images, they loose the lazy loading options of the assets components.
> fix: support only paste text
